<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<c:if test="${not empty error }">

	<div class="alert alert-warning alert-dismissible fade show"
		role="alert">
		<span>${error }</span>
		<button type="button" class="close" data-dismiss="alert"
			aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
</c:if>
<c:if test="${not empty success }">
	<div class="alert alert-success alert-dismissible fade show"
		role="alert">
		<h4 class="alert-heading">Отлично!</h4>
		<p>${success }</p>
		<hr>
		<p class="mb-0">Успехов в игре!.</p>
		<button type="button" class="close" data-dismiss="alert"
			aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
</c:if>
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="${pageContext.request.contextPath}${office.imageURL}"
	class="img-fluid" alt="Responsive image" usemap="#userNavigation">
<c:if test="${office.level eq 1 }">
	<map name="userNavigation">
		<area title="Ваш бизнес"
			href="${pageContext.request.contextPath}/office/monitor"
			coords="416,531,455,519,742,521,752,790,464,805,425,804" shape="poly">
		<area title="Рынок программистов"
			href="${pageContext.request.contextPath}/programmer/market"
			coords="1035,834,1034,805,1059,756,1049,749,1044,736,1047,721,1058,712,1073,705,1093,702,1113,697,1127,697,1144,697,1175,699,1188,702,1158,693,1198,705,1207,712,1219,721,1234,727,1244,743,1239,763,1236,773,1215,777,1205,787,1207,797,1202,817,1190,824,1147,843"
			shape="poly">
		<area title="Рынок проектов"
			href="${pageContext.request.contextPath}/projects/home"
			coords="966,868,1102,856,1013,827,995,827,940,809,912,831,920,849"
			shape="poly">
		<area title="Рынок мотиваторов"
			href="${pageContext.request.contextPath}/motivator/market"
			coords="69,919,16,895,16,860,28,855,28,814,48,785,170,773,211,783,228,809,235,853,240,899"
			shape="poly">
		<area title="Мои Проекты"
			href="${pageContext.request.contextPath}/userProjects/"
			coords="1547,270,1118,280,1126,530,1549,535" shape="poly">
	</map>
</c:if>
<c:if test="${office.level eq 2 }">
	<map name="userNavigation">
		<area title="Твой бизнес"
			href="${pageContext.request.contextPath}/office/monitor"
			coords="492,874,495,574,969,570,975,857" shape="poly">
		<area title="Рынок мотиваторов"
			href="${pageContext.request.contextPath}/motivator/market"
			coords="-2,637,39,635,48,621,37,601,39,576,37,528,41,396,56,367,217,367,232,401,229,525,232,587,214,621,261,638,258,1080,2,1078"
			shape="poly">
		<area title="Рынок проектов"
			href="${pageContext.request.contextPath}/projects/home"
			coords="999,905,994,755,1031,744,1257,747,1276,767,1272,786,1250,794,1253,878,1230,900,1065,890,1060,907"
			shape="poly">
		<area title="Рынок прграммистов"
			href="${pageContext.request.contextPath}/programmer/market"
			coords="1309,954,1284,919,1282,881,1292,863,1333,861,1342,876,1404,874,1445,927,1442,958"
			shape="poly">
		<area title="Мои проекты"
			href="${pageContext.request.contextPath}/userProjects/"
			coords="1484,54,1795,0,1917,0,1917,793,1496,771" shape="poly">
	</map>
</c:if>
<c:if test="${office.level eq 3 }">
	<map name="userNavigation">
		<area title="Твой бизнес"
			href="${pageContext.request.contextPath}/office/monitor"
			coords="258,686,258,360,940,375,946,671" shape="poly">
		<area title="Рынок мотиваторов"
			href="${pageContext.request.contextPath}/motivator/market"
			coords="81,762,76,618,110,594,110,503,143,506,148,601,158,603,178,577,188,472,215,469,222,579,246,604,241,745"
			shape="poly">
		<area title="Рынок проектов"
			href="${pageContext.request.contextPath}/projects/home"
			coords="1138,791,987,767,1074,747,1238,778" shape="poly">
		<area title="Рынок программистов"
			href="${pageContext.request.contextPath}/programmer/market"
			coords="1245,774,1264,749,1298,706,1343,679,1379,688,1493,696,1504,708,1489,788,1425,803,1253,784"
			shape="poly">
		<area title="Мои проекты"
			href="${pageContext.request.contextPath}/userProjects/"
			coords="1479,688,1482,275,1918,235,1918,737,1506,712" shape="poly">
	</map>
</c:if>
<!--  
<script type="text/javascript">
	$(document).ready(
			function() {
				var clock = $("#clockTimer");
				var image = $("#image");
				var imageW = $(image).width();
				var imageH = $(image).height();
				setSizeClock();
				function setSizeClock() {
					console.log("set");
					var imageHe = 1080;
					if ($(image).height() != imageHe) {
						var percentH = imageHe / 100;
						var diffHPercent = (imageHe - $(image).height())
								/ percentH;
						var clockB = parseFloat($(clock).css("bottom"));
						var clockBP = clockB / 100;
						clockBP = clockBP * diffHPercent;
						clockBP = clockB - clockBP;
						$(clock).css("bottom", clockBP + 1 + "px");
						var clockR = parseFloat($(clock).css("right"));
						var clockRP = clockR / 100;
						clockRP = clockRP * diffHPercent;
						clockRP = clockR - clockRP;
						$(clock).css("right", clockRP + "px");
						var clockW = $(clock).width();
						var clockH = $(clock).height();
						var clockSize = parseFloat($(clock).css('font-size'));
						clockW = clockW - (clockW / 100 * diffHPercent);
						clockH = clockH - (clockH / 100 * diffHPercent);
						clockSize = clockSize
								- (clockSize / 100 * diffHPercent);
						$(clock).css("width", clockW + "px");
						$(clock).css("height", clockH + "px");
						$(clock).css("font-size", clockSize + "px");
					}
				}
				function resizeClock() {
					if ($(image).height() != imageH) {
						var percentH = imageH / 100;
						var diffHPercent = (imageH - $(image).height())
								/ percentH;
						var clockB = parseFloat($(clock).css("bottom"));
						var clockBP = clockB / 100;
						clockBP = clockBP * diffHPercent;
						clockBP = clockB - clockBP;
						console.log("imWi " + $(image).width() + " imHE "
								+ $(image).height());
						$(clock).css("bottom", clockBP + "px");

						var clockR = parseFloat($(clock).css("right"));
						var clockRP = clockR / 100;
						clockRP = clockRP * diffHPercent;
						clockRP = clockR - clockRP;
						$(clock).css("right", clockRP + "px");

						var clockW = $(clock).width();
						var clockH = $(clock).height();
						var clockSize = parseFloat($(clock).css('font-size'));

						clockW = clockW - (clockW / 100 * diffHPercent);
						clockH = clockH - (clockH / 100 * diffHPercent);
						clockSize = clockSize
								- (clockSize / 100 * diffHPercent);

						$(clock).css("width", clockW + "px");
						$(clock).css("height", clockH + "px");
						$(clock).css("font-size", clockSize + "px");

						imageH = $(image).height();

					}
					/* else if($(image).height()>imageH){
						var percentH = imageH/100;
						var diffHPercent = ($(image).height()-imageH)/percentH;
						var clockB = parseFloat($(clock).css("bottom"));
						var clockBP = clockB/100;
						clockBP = clockBP*diffHPercent;
						clockBP = clockB+clockBP;
						console.log(clockBP+"imW "+imageH+" imHE "+$(window).height());
						
						$(clock).css("bottom",clockBP+"px");
						
						var clockR = parseFloat($(clock).css("right"));
						var clockRP = clockR/100;
						clockRP = clockRP*diffHPercent;
						clockRP = clockR+clockRP;
						$(clock).css("right",clockRP+"px");
						
						
						var clockW = $(clock).width();
						var clockH = $(clock).height();
						var clockSize = parseFloat($(clock).css('font-size'));
						
						clockW = clockW+(clockW/100*diffHPercent);
						clockH = clockH+(clockH/100*diffHPercent);
						clockSize = clockSize+(clockSize/100*diffHPercent);
						
						$(clock).css("width",clockW+"px");
						$(clock).css("height",clockH+"px");
						$(clock).css("font-size",clockSize+"px");
						
						imageH=$(image).height();
					} */
				}

				$(window).resize(function() {
					resizeClock();
				});

			});
</script>
-->